#!/bin/bash

for src in $(find $HOME/.dotfiles/_copy_only -type f); do
  rel=`realpath --relative-to=$HOME/.dotfiles/_copy_only $src`
  dst=$HOME/$rel
  parent=${dst%/*}
  if [ -f $dst ]; then
    if [ $src -nt $dst ]; then
      echo "dotfiles: $dst might be outdated"
    fi
  else
    mkdir -p $parent
    cp $src $dst
  fi
done

# Install powerline-status, and make symlink manually
# NOTE: symlink won't be created in `editable` install
pip3 install --user --editable=$HOME/.powerline-install \
  && ln -nfs $HOME/.powerline-install/scripts/powerline $HOME/.local/bin

